batch_size: 32
bspline_degree: 5
bspline_num_control_points_desired: 22
clip_grad: false
conditioning_type: default
context_combined_out_dim: 128
context_ee_goal_pose: false
context_ee_goal_pose_act: relu
context_ee_goal_pose_n_layers: 2
context_ee_goal_pose_out_dim: 128
context_q_out_dim: 128
context_qs: true
context_qs_act: relu
context_qs_n_layers: 2
cvae_latent_dim: 32
dataset_dir: /home/hong/Projects/MotionPlanningDiffusion/mpd-splines-public/data_trajectories_hcj/piper_472
dataset_file_merged: dataset_merged_processed.hdf5
debug: false
device: cuda:0
generative_model_class: GaussianDiffusionModel
git_hash: 3676cbf371b0e2a98663d8cef666f671e004e3da
git_url: https://github.com/joaoamcarvalho/mpd-splines-public.git
loss_cvae_kl_weight: 0.1
lr: 0.0003
n_diffusion_steps: 100
n_task_samples: -1
num_T_pts: 256
num_train_steps: 10000
parametric_trajectory_class: ParametricTrajectoryBspline
predict_epsilon: true
preload_data_to_device: true
reload_data: false
results_dir: logs_piper/1
seed: 1
steps_til_ckpt: 20000
steps_til_summary: 1000000
summary_class: SummaryTrajectoryGeneration
unet_dim_mults_option: 1
unet_input_dim: 32
use_amp: false
use_ema: true
variance_schedule: cosine
wandb_entity: mpd-splines
wandb_mode: disabled
wandb_project: train_piper_diffusion
